### ISSUE TITLE
Nextra's search shows duplicated results

### ISSUE THREAD

**Issue by kamilkisiela** [the-guild-org/the-guild-components#1484]
![Screenshot 2024-04-16 at 09 55 02](https://github.com/the-guild-org/docs/assets/8167190/8f07be35-0880-48c2-a799-0e5a9db96f79)

It's an example from Hive where it shows 4 results linking to the same page for `schema` phrase.

**Comment by dimaMachina** [comment]
Search is migrated to Pagefind, so this problem should be gone https://github.com/shuding/nextra/issues/2524
