### ISSUE TITLE
storybook is broken?

### ISSUE THREAD

**Issue by saihaj** [the-guild-org/the-guild-components#230]
Tried on chrome and safari and I just see a spinner.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/44710980/139372454-7ee1e269-0f29-4d3d-b062-060216b1c8fe.png">

**Comment by B2o5T** [comment]
@saihaj On my side it's working fine in chrome and firefox. Can you confirm that the bug still exist?

![image](https://user-images.githubusercontent.com/7361780/141541909-cb4cfcfb-055f-4f18-91a3-41120b8ca346.png)

**Comment by saihaj** [comment]
@B2o5T I tried on Chrome `Version 95.0.4638.69`, Safari `Version 15.1 (17612.2.9.1.20)`and Firefox `94.0b6` and I just see a spinner and in console I see  
![image](https://user-images.githubusercontent.com/44710980/141603940-3d1395b1-8b1c-4f15-831e-51dea4f59a4f.png)

**Comment by orenelbaum** [comment]
I'm seeing the same thing as @saihaj .

**Comment by dotansimha** [comment]
can confirm. https://the-guild-components-storybook.vercel.app/ 

![image](https://user-images.githubusercontent.com/3680083/143733891-5df37f24-4044-4f1b-b82b-55ed6a0f88d7.png)

@B2o5T

**Comment by B2o5T** [comment]
I can’t reproduce it on local

- I took the latest version of the `main` branch
- `yarn && yarn storybook`
- `npx serve dist-storybook`

Everything fine
