### ISSUE TITLE
navigation menu is opened behind header

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-components#371]
![8DF13F88-F1AB-4ECC-A588-ADE67AE9B82F](https://user-images.githubusercontent.com/14338007/167602841-57b598eb-f794-4a0e-9e83-d5868334fcd4.jpeg)

**Comment by B2o5T** [comment]
Hm, i just tested yoga 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/7361780/167605747-b4016be5-5130-4df0-8492-27f5ac56ac50.png">

**Comment by n1ru4l** [comment]
I opened the other menu

**Comment by B2o5T** [comment]
@n1ru4l my bad, could reproduce, will fix it now
