### ISSUE TITLE
Bug: seems like clicking on links takes longer to respond?

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/the-guild-components#527]
To reproduce:
1. Use any website
2. Click on a link
3. It takes a few seconds to get to the actual page. I think eventually it's not JS-loading the page and does a full page load.

> Note: loading the page without a link, replies instantly.

**Comment by charlypoly** [comment]
Repro: 

https://user-images.githubusercontent.com/1252066/197494244-54ba4171-2233-4aa4-b439-b46c49f047a6.mov

**Comment by dotansimha** [comment]
This happened due to a `lowercase` fix we applied to the router. Fixed in https://github.com/the-guild-org/the-guild-website/commit/212018a8e6aa847dbae023c6175e6e0dde1c3229
